### ISSUE TITLE
Is it possible to get the texture from the UV construction?

### ISSUE THREAD

**Issue by lthiet** [mworchel/xatlas-python#10]
Thanks a lot for the bindings!

I am using the bindings to create a mesh with UV mapping from 3d scans. For each point, I have an associated color and with open3d I managed to make a colored mesh.

![image](https://user-images.githubusercontent.com/26815719/154969544-a119397c-6f62-45ed-875e-7cfdb62a5345.png)

Now I am using Atlas to generate UV mapping, but I don't know how I can get a texture from it so I can use it in Unity for example.

Do you know how I could do that?

**Comment by mworchel** [comment]
Hi,

transferring vertex attributes to texture space is, as far as I know, impossible with xatlas.

However, you can take the UV mapped mesh and try using Meshlab like here: https://www.hisshadow.com/vertex-colour-to-texture/. I didn't try this tutorial, but it should do the trick. There are also Python bindings for Meshlab, see https://github.com/cnr-isti-vclab/PyMeshLab.

Hope this helps.

**Comment by lthiet** [comment]
That worked exactly as described! Thanks a lot!

**Comment by jh27kim** [comment]
Hi, i tried your method but the texture map I get seems a little weird 
Is this correct ? Maybe this is because I'm using imperfect meshes?

![image](https://github.com/mworchel/xatlas-python/assets/58447982/d2b682af-3709-4441-89b1-f16354b07abc)
