### ISSUE TITLE
UV and normal parameters in "add_mesh" swapped

### ISSUE THREAD

**Issue by impiaaa** [mworchel/xatlas-python#13]
Similar to #4, the binding says that the last two parameters are "uvs" and "normals":
https://github.com/mworchel/xatlas-python/blob/752d97089a57e91bdbfbbda5a90ed8fa14f8b772/src/atlas.cpp#L264
but `Atlas::addMesh` actually takes "normals" and then "uvs":
https://github.com/mworchel/xatlas-python/blob/752d97089a57e91bdbfbbda5a90ed8fa14f8b772/src/atlas.cpp#L45-L48

**Comment by mworchel** [comment]
Thanks for reporting. The issue is fixed in version 0.0.8.

**Comment by impiaaa** [comment]
Thanks for the fix!
