### ISSUE TITLE
Incorrect parameter name

### ISSUE THREAD

**Issue by yongsiang-fb** [mworchel/xatlas-python#4]
In this line, the third argument should actually be `normals` rather than `uvs`. The fourth argument should actually be `uvs` rather than `normals`.

https://github.com/mworchel/xatlas-python/blob/b3c81234f8d40e07b23e96600a48b438bab38f69/src/module.cpp#L145

**Comment by mworchel** [comment]
Good catch, thank you! It's fixed in the 0.0.5 release.
