### ISSUE TITLE
Support for `xatlas::AddUvMesh`?

### ISSUE THREAD

**Issue by yongsiang-fb** [mworchel/xatlas-python#5]
Hi,

Thanks for making the great Python binding!

Would it be possible to add support to the `xatlas::AddUvMesh` method, please? It is quite useful when repacking existing textures. The current binding only supports `xatlas::AddMesh`.

**Comment by mworchel** [comment]
Hi,

I haven't really looked into that function. What is the function's purpose? Add a mesh that already has a parametrization to the atlas? 

I will see what I can do but also welcome a PR.

**Comment by yongsiang-fb** [comment]
> Add a mesh that already has a parametrization to the atlas?
Yes, you are right. Basically this would allow us to pack existing atlases from multiple meshes into a new atlas or atlases.

Thanks!

**Comment by mworchel** [comment]
Hi,

the bindings for `AddUvMesh` are finally implemented in release v0.0.6.
