### ISSUE TITLE
UV Layout Export as transparent png file

### ISSUE THREAD

**Issue by kashyappiyush1998** [mworchel/xatlas-python#9]
I was trying to use blender python as my UV unwrapped, but when I need UV layout to be exported it needs a display to draw, which is not feasible for me. Then I discovered that xatlas is also able to do that, but I do not know if it is able to export UV as a layout. It would be very helpful for me to have this feature added.
Thank You

**Comment by mworchel** [comment]
Hi, 

could you be provide an example of what specifically you expect to export? The only "image-related" binding I currently have is `chart_image`, which is however only a debug image.

Is your request related to #10?
